### PR TITLE
feat:add page title component

### PR DESCRIPTION
**Pull request by Lovelyfin00**
- Added the page title component since it's reusable across all pages

### Screenshots
<br/>

image

### CODE REVIEW

**Comment by CatherineKiiru** [comment]
@Lovelyfin00 add the route to the page title

**Comment by Lovelyfin00** [comment]
> Hi @Lovelyfin00 add the route to the page title component. Check this out https://nextjs.org/docs/pages/building-your-application/routing

Hi @CatherineKiiru 
It's a component that's going to be reused in other components. There's no need for me to add a route to it

**Comment by CatherineKiiru** [comment]
Can you create a route for the tech page you're working on? That way we can review the reusable component in a real use case

**Comment by Lovelyfin00** [comment]
> @Lovelyfin00 Can you create a route for the tech page you're working on and add the reusable component? That way we can review the reusable component in a real use case

I have already done that
I created a new PR with the tech page. Included a video demo too. You can check the latest PR. I tagged you

**Comment by Lovelyfin00** [comment]
I'll close this PR now

**Pull request closed without merging**
